# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c761ad5846268e3e0dbc9e3c58fc036243268ed6f678e243425bcc90cf4e5a63451ef80bb7b7dd9880259c67e5c2514c969aed6de0064f7f4d59ae1dec6cbe7a

test:
  secret_key_base: 0de5c0f44f85a439a45fef7b43f6c94a4f9cfd9cc5c0b6ef53afc405269a73a9bf492e96c6e991b913cf120dbf951dbe2e67aa71834198bb86bcb5d720546f6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
